spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-demo-service
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'